name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      node-version: 20.x

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.node-version }} and setup .npmrc
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install deps
        run: yarn --immutable

      - name: Build files
        run: yarn build

      - name: Run publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
